name: Build NekoX APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Create Keystore Directory and Decode
      env:
        KEYSTORE_BASE64: ${{ secrets.KEY_STORE }}
      run: |
        mkdir -p TMessagesProj/config
        echo "$KEYSTORE_BASE64" | base64 --decode > TMessagesProj/config/release.keystore

    - name: Inject API Keys & Change App Name
      env:
        MY_API_ID: ${{ secrets.TELEGRAM_API_ID }}
        MY_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
      run: |
        # 1. Inject real Telegram API ID and API HASH
        sed -i "s/public static int APP_ID = 4;/public static int APP_ID = ${MY_API_ID};/g" TMessagesProj/src/main/java/org/telegram/messenger/BuildVars.java
        sed -i 's/public static String APP_HASH = ".*";/public static String APP_HASH = "'"${MY_API_HASH}"'";/g' TMessagesProj/src/main/java/org/telegram/messenger/BuildVars.java

        # 2. Change App Name for home screen to recognize it easily
        sed -i 's/<string name="AppName">Telegram<\/string>/<string name="AppName">NekoX Custom<\/string>/g' TMessagesProj/src/main/res/values/strings.xml

    - name: Build Main App Only
      run: ./gradlew :TMessagesProj_App:assembleAfatRelease -PRELEASE_STORE_PASSWORD="${{ secrets.KEY_PASS }}" -PRELEASE_KEY_ALIAS="${{ secrets.KEY_ALIAS }}" -PRELEASE_KEY_PASSWORD="${{ secrets.KEY_PASS }}"

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NekoX-Official-Release
        path: "**/build/outputs/apk/**/*.apk"
        
